### ISSUE TITLE
The url https://www.linkedin.com/learning-api/... no longer works 

### ISSUE THREAD

**Issue by h27-webdev** [liranbg/linkedin-learning-downloader#17]
The above url now returns 404 Csrf check failed...!!!!

**Comment by liranbg** [comment]
resolved #21

**Comment by sticker592** [comment]
I'm getting 404 error still but not because of csrf. An example link that returned 404:
'https://www.linkedin.com/learning-api/detailedCourses??fields=fullCourseUnlocked,releasedOn,exerciseFileUrls,exerciseFiles&addParagraphsToTranscript=true&courseSlug=https://www.linkedin.com/learning/learning-dot-net-programming&q=slugs'
